### PR TITLE
Various improvements

### PR DESCRIPTION
**Pull request by CyberShadow**
Hi, here is my work so far for your consideration. For details, see the commit messages. Please let me know what you think, or if you have any questions.

### CODE REVIEW

**Comment by tsukimizake** [comment]
My pc went broken yesterday, so I can't check it for now. Please wait for a
few days...

**Comment by CyberShadow** [comment]
No problem. Sorry to hear about your PC.

**Comment by CyberShadow** [comment]
I've added another commit, which improves import path detection, please see its commit message for details.

**Comment by CyberShadow** [comment]
I've added another small fix, to stop Emacs asking whether to kill dcd-server on exit.

Sorry, have you had a chance to look at this yet? If you like, I can take over maintaining this package. Or maybe we could move it to https://github.com/Emacs-D-Mode-Maintainers.

**Comment by tsukimizake** [comment]
I'm sorry for keeping you await so long. I checked it. Thanks!

> If you like, I can take over maintaining this package.

That's fair enough. It seems you know far more about Dlang and DCD than me.
Shall I "Transfer ownership" to you?

**Comment by CyberShadow** [comment]
> Shall I "Transfer ownership" to you?

Hmm, would that break MELPA? I'm not sure how that works.

@russel, what do you think of the idea above?

I think you also could just grant push access.

**Comment by tsukimizake** [comment]
That would be better. I'll do it.

**Comment by CyberShadow** [comment]
Thanks :)

**Pull request merged**
